---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elite-dep
  label:
    app: elite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elite
  template:
    metadata:
      labels:
        app: elite
    spec:
      containers:
      - name: elite
        image: devops1117/elite:v_1.0
        ports:
        - containerPort: 80   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: elite-svc
  label:
    app: elite
spec:
  selector:
    app: elite
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 80
  type: LoadBalancer
